config/routes.rb
Rails.application.routes.draw do
  resources :reaches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "static_pages#home" 
  match '/home' , to: 'static_pages#home', via: 'get'
  match '/aboutus' , to: 'static_pages#aboutus', via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reach.rb
class Reach < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reaches_controller.rb
class ReachesController < ApplicationController
  before_action :set_reach, only: [:show, :edit, :update, :destroy]

  # GET /reaches
  # GET /reaches.json
  def index
    @reaches = Reach.all
  end

  # GET /reaches/1
  # GET /reaches/1.json
  def show
  end

  # GET /reaches/new
  def new
    @reach = Reach.new
  end

  # GET /reaches/1/edit
  def edit
  end

  # POST /reaches
  # POST /reaches.json
  def create
    @reach = Reach.new(reach_params)

    respond_to do |format|
      if @reach.save
        format.html { redirect_to @reach, notice: 'Reach was successfully created.' }
        format.json { render :show, status: :created, location: @reach }
      else
        format.html { render :new }
        format.json { render json: @reach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reaches/1
  # PATCH/PUT /reaches/1.json
  def update
    respond_to do |format|
      if @reach.update(reach_params)
        format.html { redirect_to @reach, notice: 'Reach was successfully updated.' }
        format.json { render :show, status: :ok, location: @reach }
      else
        format.html { render :edit }
        format.json { render json: @reach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reaches/1
  # DELETE /reaches/1.json
  def destroy
    @reach.destroy
    respond_to do |format|
      format.html { redirect_to reaches_url, notice: 'Reach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reach
      @reach = Reach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reach_params
    if params[:reach][:websitepurpose] != nil
       params[:reach][:websitepurpose] = params[:reach][:websitepurpose].join(',')
    end
    if params[:reach][:objectiveachieve] != nil
       params[:reach][:objectiveachieve] = params[:reach][:objectiveachieve].join(',')
    end
      params.require(:reach).permit(:whatyouwant, :howlongrun, :triedonline, :everspentmoney, :runningwebsite, :websitepurpose, :objectiveachieve, :investatleast, :name, :phonenumber, :whatsappnumber, :email)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def home
	
end

def aboutus
	
end

def faq
	
end

def thankyou
	
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reaches_helper.rb
module ReachesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Legendsonly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

     <!-- <script src="https://kit.fontawesome.com/6a7478929c.js" crossorigin="anonymous"></script> -->
     <script src="https://use.fontawesome.com/fc6d352727.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Muli|Oswald&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One&display=swap" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1">

     	<style type="text/css">
   	 a {
  text-decoration: none;
  background-color: transparent;
  -webkit-text-decoration-skip: objects;
}

a:hover {
  text-decoration: none;
}


  .navbackground{
     background-color: #ffffff;
     border-bottom: 1.5px solid #ffd700;
     -webkit-box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
-moz-box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
  }



.navbar-brand1 {
  display: inline-block;
  padding-top: 0.3125rem;
  padding-bottom: 0.3125rem;
  margin-right: 1rem;
  font-size: 1.25rem;
  line-height: inherit;
  white-space: nowrap;
}




.navbar-light .navbar-brand1{
color: #000; 
font-weight: 700;
}

.navbar-scroll{
color: #000; 
font-weight: 700;
}

.navbar-light .navbar-brand:focus, .navbar-light .navbar-brand:hover {
  color: white;
}

.navbar-light .navbar-scroll:focus, .navbar-light .navbar-scroll:hover {
  color: #343a40;
}

.navbar-light .navbar-nav .nav-link {
  color: #000000;
  font-weight: 400;
  font-size: 14px;
  transition: border-color .5s ease-in-out;
    -webkit-transition: border-color .5s ease-in-out;
    -moz-transition: border-color .5s ease-in-out;
  border-bottom: 4px solid transparent;
}

.navlinkscroll{
  color: #343a40;
  
}

.navbar-light .navbar-nav .nav-link:focus {
	transition: color .5s ease-in-out;
  color: #fdbd1e;
  font-weight: 300;
}

 .navbar-light .navbar-nav .nav-link:hover {
 	transition: color .5s ease-in-out;
  color: #000000;
  font-weight: 500;
}

.navbar-light .navbar-nav .nav-link.disabled {
  color: rgba(0, 0, 0, 0.3);
}

.navbar-light .navbar-nav .show > .nav-link,
.navbar-light .navbar-nav .active > .nav-link,
.navbar-light .navbar-nav .nav-link.show,
.navbar-light .navbar-nav .nav-link.active {
  color: #000000;
  font-weight: 500;
 }


 .navbar-toggler {
  border: none;
  background: transparent !important;
}
.navbar-toggler:hover {
  background: transparent !important;
}
.navbar-toggler .icon-bar {
  display:block;
  background-color: #ffd700;
  width: 26px;
  height: 2px;
  transition: all 0.2s;
}
.navbar-toggler .icon-bar+.icon-bar{
  margin-top: 5px;
}
.navbar-toggler .top-bar {
  transform: rotate(45deg);
  transform-origin: 10% 10%;
}
.navbar-toggler .middle-bar {
  opacity: 0;
}
.navbar-toggler .bottom-bar {
  transform: rotate(-45deg);
  transform-origin: 10% 90%;
}
.navbar-toggler.collapsed .top-bar {
  transform: rotate(0);
}
.navbar-toggler.collapsed .middle-bar {
  opacity: 1;
}
.navbar-toggler.collapsed .bottom-bar {
  transform: rotate(0);
}

 @media only screen and (min-width : 100px) and (max-width : 600px) {

.navbar-brand1 {
  display: inline-block;
  padding-top: 0.3125rem;
  padding-bottom: 0.3125rem;
  margin-right: 1rem;
  font-size: 14px;
  line-height: inherit;
  white-space: nowrap;
}

}

</style>

  </head>

    	<nav class="navbar navbar-light navbar-expand-lg fixed-top navbackground navshadow">
      <div class="container">
        <a class="navbar-brand1" href="/" style=""><img src="https://res.cloudinary.com/nikasemo/image/upload/v1579479826/marketinglegendslogo_maubwt.png" style="height: 100%; margin-right:3px; height: 57px;">
          <span style="position:relative; top: 0px; color: #ffd700;">The Marketing Legends</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
       
            <li class="nav-item">
              <a class="nav-link" target="_blank" href="/aboutus">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!">Contact Us</a>
            </li>
          </ul>
           <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#!" target="_blank"><span><i class="fa fa-facebook-official" style="margin-left: 9px;" aria-hidden="true"></i></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!" target="_blank"><span><i class="fa fa-twitter-square" style="margin-left: 9px;" aria-hidden="true"></i></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#!"><span><i class="fa fa-instagram" style="margin-left: 5px;" aria-hidden="true"></i></span></a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <% if notice %>
	<div class="alert alert-success alert-dismissible" role="alert" style="position: absolute; top: 100px; z-index: 99999;>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	  <p class="notice"><%= notice %></p>
	</div>
	<% end %>

  <body style="font-family: 'Montserrat', sans-serif; background-color: #F9F6F6;">


    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reaches/_form.html.erb
<%= form_for(reach) do |f| %>
  <% if reach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reach.errors.count, "error") %> prohibited this reach from being saved:</h2>

      <ul>
      <% reach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label style="font-weight: 600;">What do you want to do online with your business or organization?</label>
    <span style="color: #d9b806; font-size: 12px;"><br>Eg. Build a website to get clients for my business / Build a website to get customers to for my product / Build a website to get support for my organization (NGO, School etc)</span>
    <%= f.text_area :whatyouwant, :class => "form-control", :rows => "3", :placeholder => "What do you want to do .."  %>
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">How long have you been running your business / organization?</label><br>
    <input type="radio" name="reach[howlongrun]" id="reach_howlongrun" value="1 Year or less"> 1 Year or less
  <input type="radio" name="reach[howlongrun]" id="reach_howlongrun" value="1 - 2 years" style="margin-left: 10px;"> 1 - 2 years
  <input type="radio" name="reach[howlongrun]" id="reach_howlongrun" value="3 - 4 years" style="margin-left: 10px;"> 3 - 4 years
  <input type="radio" name="reach[howlongrun]" id="reach_howlongrun" value="More than years" style="margin-left: 10px;"> 5 or more years
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">Have you ever tried any online methods to promote your business?</label><br>
    <input type="radio" name="reach[triedonline]" id="reach_triedonline" value="Yes"> Yes
  <input type="radio" name="reach[triedonline]" id="reach_triedonline" value="No" style="margin-left: 10px;"> No
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">Have you ever spent money to build a website, or do any online marketing?</label><br>
    <input type="radio" name="reach[everspentmoney]" id="reach_everspentmoney" value="Yes"> Yes
  <input type="radio" name="reach[everspentmoney]" id="reach_everspentmoney" value="No" style="margin-left: 10px;"> No
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">Do you have a website running?</label><br>
    <input type="radio" name="reach[runningwebsite]" id="reach_runningwebsite" value="Yes"> Yes
  <input type="radio" name="reach[runningwebsite]" id="reach_runningwebsite" value="No" style="margin-left: 10px;"> No
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">What is the website's purpose and what is your objective for having a website?</label><br>
    <input type="checkbox" name="reach[websitepurpose][]" id="reach_websitepurpose_1" 
    value="To Make Sales"> To make sales / get clients for my business<br>
    <input type="checkbox" name="reach[websitepurpose][]" id="reach_websitepurpose_2" 
    value="To build an audience I can consistently market to."> To build an audience I can consistently market to.<br>
    <input type="checkbox" name="reach[websitepurpose][]" id="reach_websitepurpose_3" 
    value="To build a personal brand"> To build a personal brand<br>
    <input type="checkbox" name="reach[websitepurpose][]" id="reach_websitepurpose_4" 
    value="To build my company's brand"> To build my company's brand<br>
    <input type="checkbox" name="reach[websitepurpose][]" id="reach_websitepurpose_5" 
    value="To get support for my organization"> To get support for my organization (NGO, Non Profit, School etc)<br>
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">What goals do you want to achieve with your website?</label><br>
    <input type="checkbox" name="reach[objectiveachieve][]" id="reach_objectiveachieve_1" 
    value="Build a consistent system to generate sales for my business"> Build a consistent system to generate sales for my business<br>
    <input type="checkbox" name="reach[objectiveachieve][]" id="reach_objectiveachieve_2" 
    value="Increase my current sales by 100 - 200%"> Increase my current sales by 100 - 200%<br>
    <input type="checkbox" name="reach[objectiveachieve][]" id="reach_objectiveachieve_4" 
    value="Build a large audience I can consistently market to"> Build a large audience I can consistently market to<br>
    <input type="checkbox" name="reach[objectiveachieve][]" id="reach_objectiveachieve_3" 
    value="Communicate my brand's message to a huge audience"> Communicate my brand's message to a huge audience<br>
    <input type="checkbox" name="reach[objectiveachieve][]" id="reach_objectiveachieve_5" 
    value="Get external help for my organization (School, NGO, Non Profit)"> Get help for my organization (School, NGO, Non Profit)<br>
  </div>

  <div class="form-group">
    <label style="font-weight: 600;">Can you invest at least 3000 cedis a year to make this work?</label>
    <br>
    <input type="radio" name="reach[investatleast]" id="reach_investatleast" value="Yes (If I can figure out how to grow"> Yes. (If I can figure out how to grow my Business / Brand)<br>
  <input type="radio" name="reach[investatleast]" id="reach_investatleast" value="No, I wont" style=""> No, I wont.
  </div>
  <br>
  <hr>
  <h4>Your contact information</h4>
  <br>
  <div class="form-group">
    <label style="font-weight: 500;">Name</label>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Your name" %>
  </div>

  <div class="form-group">
    <label style="font-weight: 500;">Phone Number</label>
    <%= f.text_field :phonenumber, :class => "form-control", :placeholder => "Your Phone Number" %>
  </div>

  <div class="form-group">
    <label style="font-weight: 500;">WhatsApp Number</label> <span style="font-size: 12px;">(Optional)</span>
    <%= f.text_field :whatsappnumber, :class => "form-control", :placeholder => "Your WhatsApp Number" %>
  </div>

  <div class="form-group">
    <label style="font-weight: 500;">Email</label>
    <%= f.text_field :email, :class => "form-control", :placeholder => "Your Email" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", :class => "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/reaches/edit.html.erb
<h1>Editing Reach</h1>

<%= render 'form', reach: @reach %>

<%= link_to 'Show', @reach %> |
<%= link_to 'Back', reaches_path %>

app/views/reaches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reaches</h1>

<table>
  <thead>
    <tr>
      <th>Whatyouwant</th>
      <th>Howlongrun</th>
      <th>Triedonline</th>
      <th>Everspentmoney</th>
      <th>Runningwebsite</th>
      <th>Websitepurpose</th>
      <th>Objectiveachieve</th>
      <th>Investatleast</th>
      <th>Name</th>
      <th>Phonenumber</th>
      <th>Whatsappnumber</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reaches.each do |reach| %>
      <tr>
        <td><%= reach.whatyouwant %></td>
        <td><%= reach.howlongrun %></td>
        <td><%= reach.triedonline %></td>
        <td><%= reach.everspentmoney %></td>
        <td><%= reach.runningwebsite %></td>
        <td><%= reach.websitepurpose %></td>
        <td><%= reach.objectiveachieve %></td>
        <td><%= reach.investatleast %></td>
        <td><%= reach.name %></td>
        <td><%= reach.phonenumber %></td>
        <td><%= reach.whatsappnumber %></td>
        <td><%= reach.email %></td>
        <td><%= link_to 'Show', reach %></td>
        <td><%= link_to 'Edit', edit_reach_path(reach) %></td>
        <td><%= link_to 'Destroy', reach, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reach', new_reach_path %>

app/views/reaches/new.html.erb
<style type="text/css">

nav {
	display: none;
}

.navbackground {
}
	
.aduins{

 background:linear-gradient(90deg,rgba(255, 217, 0,0.9),rgba(255, 217, 0,0.2)),url(https://res.cloudinary.com/nikasemo/image/upload/c_scale,h_965/v1579482402/00100dPORTRAIT_00100_BURST20190918153958546_COVER_1_i5vkft.jpg);
  background-position:center;
  min-height: 350px;
  padding: 50px;
}

.aduinsh1 {
      text-align: left; 
      color: white; 
      position: relative; 
      top: 140px; 
      font-weight: 300; 
      font-family: 'Lalezar', cursive;
      font-size: 50px; 
      line-height: 30px;
    }

.aduinsp1 {
  text-align: left; 
  color: white;
  font-family: 'Raleway', sans-serif;
  font-weight: 300; 
  position: relative;
  font-size: 14px; 
  top: 140px;
}

hr.worksdivider{
  height: 2px;
  background-color: #4a4a4a;
  border: 1px solid #4a4a4a;
  width: 5%;
}

@media only screen and (min-width : 100px) and (max-width : 600px) {

 .aduins{
 background:linear-gradient(90deg,rgba(255, 217, 0,0.9),rgba(255, 217, 0,0.2)),url(https://res.cloudinary.com/nikasemo/image/upload/c_scale,h_965/v1579482402/00100dPORTRAIT_00100_BURST20190918153958546_COVER_1_i5vkft.jpg);
  background-position:center;
  min-height: 350px;
  padding: 50px;
}

.aduinsh1 {
      text-align: left; 
      color: white; 
      position: relative; 
      top: 140px; 
      font-weight: 300; 
      font-family: 'Lalezar', cursive;
      font-size: 30px; 
      line-height: 30px;
    }

.aduinsp1 {
  text-align: left; 
  color: white;
  font-family: 'Raleway', sans-serif;
  font-weight: 300; 
  position: relative;
  font-size: 14px; 
  top: 140px;
}

</style>

<section class="aduins">
      <div class="container">
        <div class="row" style="margin-top: 0px">
          <div class="col-lg-12">
            <!-- <h1 style="font-weight: 700;" class="aduinsh1">
              About Us
            </h1>
            <p style="" class="aduinsp1">
              We want to help you with what we have learnt about marketing online.
            </p> -->
          </div>
        </div>
      </div>
    </section>

<br>

<div class="container">
	<div class="row">
		<div class="col-lg-8">
			<h3>Kindly fill this form.</h3>
			<p>We want to help you!</p>

			<%= render 'form', reach: @reach %>

			
		</div>
	</div>
</div>

app/views/reaches/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-md-6 offset-md-3">
            <style type="text/css">
        
        #sidebar {
          display: none;
          }
          
      </style>

      <br><br><br><br><br>
      <p style="text-align: center;">
        <img src="https://res.cloudinary.com/nikasemo/image/upload/v1576052324/smiling-emoticon-square-face_eky0ti.png">
      </p>
      <h3 style="text-align: center;">Thank you for filling our Form, <%= @reach.name %>!</h3>
      <br>
      <p style="text-align: center; color: #4A4A4A; text-align: justify;">Welcome to Marketing Legends! 
        Just as we have been able to find you on the internet as a potential customer for our business, in that same regard, there are several hundreds or even thousands of customers and key partners you can find using the internet! The Marketing Legends will help you with this. Your website is of no practical use if there is no practical and proven way to find customers to visit it everyday..
        <br><br>
      We want to welcome you with a short orientation on how to use this powerful tool called the internet for your business / organization! We will get back to you soon!</p>
      <br>
      <p style="text-align: center;">
        <a href="/reaches/new" class="btn btn-primary">Go Back</a>
      </p>
      <br><br><br>
    </div>
  </div>
</div>

app/views/static_pages/aboutus.html.erb
<style type="text/css">
	.aduins{
 background:linear-gradient(90deg,rgba(255, 217, 0,0.9),rgba(255, 217, 0,0.2)),url(https://res.cloudinary.com/nikasemo/image/upload/c_scale,h_965/v1579482402/00100dPORTRAIT_00100_BURST20190918153958546_COVER_1_i5vkft.jpg);
  background-position:center;
  min-height: 350px;
  padding: 50px;
}

.aduinsh1 {
      text-align: left; 
      color: white; 
      position: relative; 
      top: 140px; 
      font-weight: 300; 
      font-family: 'Lalezar', cursive;
      font-size: 50px; 
      line-height: 30px;
    }

.aduinsp1 {
  text-align: left; 
  color: white;
  font-family: 'Raleway', sans-serif;
  font-weight: 300; 
  position: relative;
  font-size: 14px; 
  top: 140px;
}

hr.worksdivider{
  height: 2px;
  background-color: #4a4a4a;
  border: 1px solid #4a4a4a;
  width: 5%;
}

.holdactioninside {
	height: 200px;
	border: 7px solid #ffd700;
	text-align: center;
	-webkit-box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
-moz-box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
box-shadow: 0px 0px 35px -1px rgba(0,0,0,0.25);
}

@media only screen and (min-width : 100px) and (max-width : 600px) {

 .aduins{
 background:linear-gradient(90deg,rgba(255, 217, 0,0.9),rgba(255, 217, 0,0.2)),url(https://res.cloudinary.com/nikasemo/image/upload/c_scale,h_965/v1579482402/00100dPORTRAIT_00100_BURST20190918153958546_COVER_1_i5vkft.jpg);
  background-position:center;
  min-height: 350px;
  padding: 50px;
}

.aduinsh1 {
      text-align: left; 
      color: white; 
      position: relative; 
      top: 140px; 
      font-weight: 300; 
      font-family: 'Lalezar', cursive;
      font-size: 30px; 
      line-height: 30px;
    }

.aduinsp1 {
  text-align: left; 
  color: white;
  font-family: 'Raleway', sans-serif;
  font-weight: 300; 
  position: relative;
  font-size: 14px; 
  top: 140px;
}


}
</style>


<section class="aduins">
      <div class="container">
        <div class="row" style="margin-top: 0px">
          <div class="col-lg-12">
            <!-- <h1 style="font-weight: 700;" class="aduinsh1">
              About Us
            </h1>
            <p style="" class="aduinsp1">
              We want to help you with what we have learnt about marketing online.
            </p> -->
          </div>
        </div>
      </div>
    </section>


<div class="container">
	<div class="row" style="margin-top: 50px;">

		<div class="col-lg-8">
			<h4>About the Team</h4>
			<hr align="left" width="3%" class="worksdivider">
			<p>
				We have successfully built an online business in Ghana which manages to bring in customers and clients and gets them to pay for products and services we provide and we happily want to help you do same.
				<br><br>
				<span style="font-weight: 500;">Are you thinking of having a website?</span>
				<br>
				Do you also think that by just having a website and telling people about it, sales and marketing will automatically shoot up?<br>
				Are you frustrated by your online marketing efforts because the results you are getting are insignificant?
				<br><br>
				<span style="font-weight: 500;">Let’s rethink this.</span>
				<br>
				Let’s see our website like a weapon. Having a good sword doesn’t necessarily mean you are going to win the fight. Your ability to fight with a sword (1) and your ability to actually use that particular sword (2) are your key success factors.
				<br><br>
				<span style="font-weight: 500;">
					You shouldn’t spend money on a website until you have figured out these two.
				</span>
				<br> 
				1.	Understanding the internet and the avenues it presents you to sell your website. Crafting messages for every avenue of communication.<br>
				2.	Using your website as the sword to execute the actions in one.
				<br><br>
				<span style="font-weight: 500;">All set. Seems easy, right?</span><br>
				In my five years of freelance website development. We have encountered a lot of clients. Most of them we just built websites for. We knew most would not do well because they didnt know how to use these new tools to reach their customers and clients. It is different now!
				<br><br>
				Based on our experience and results we have generated for our business (and also other businesses we have helped) we can help you greatly; first with building the weapon - A great website and then help you reach your market, building an audience, communicating with them and get them to pay for your product or service!
				<br><br>
				<span style="font-weight: 600;">Click on the action button below lets get started talking!</span>
			</p>
			<p>
				<a href="/reaches/new" class="btn btn-lg btn-success" style="font-weight: 600;">Lets get Talking!</a>
			</p>
			<br><br><br>
		</div>

		<div class="col-lg-4">
			<img src="https://res.cloudinary.com/nikasemo/image/upload/v1579479826/marketinglegendslogo_maubwt.png" class="img-fluid">
		</div>
	</div>
</div>



<div class="row no-gutters">

	<div class="col-lg-6">
		<div class="holdactioninside">
			<br>
			<br>
			<br>
			<a href="" style="color: #ffd700; font-size: 20px;"><i class="fa fa-pencil-square" aria-hidden="true"></i> Work with Us</a>
		</div>
	</div>

	<div class="col-lg-6">
		<div class="holdactioninside">
			<br>
			<br>
			<br>
			<a href="" style="color: #ffd700; font-size: 20px;"><i class="fa fa-briefcase" aria-hidden="true"></i> Our Client Profiles</a>
		</div>
	</div>

</div>